#USE THE OFFICIAL PYTHON IMAGE AS THE BASE IMAGE
FROM python:3.9-buster  

#SET WORKING DIRECTORY IN THE CONTAINER
WORKDIR /app

#COPY THE REQUIREMENT FILE TO THE WORKING DIRECTORY
COPY requirements.txt .

#INSTALL THE REQUIRED PYTHON PACKAGES
RUN pip3 install --no-cache-dir -r requirements.txt

#COPY THE APPLICATION CODE TO THE WORKING DIRECTORY
COPY . .

#SET THE ENVIRONMENT VARIABLE FOR THE FLASK APP
ENV FLASK_RUN_HOST=0.0.0.0

#EXPOSE THE PORT ON WHICH FLASK APP WILL RUN
EXPOSE 5000

#START THE FLASK APP WHEN THE CONTAINER IS RUN
CMD ["flask", "run"]